spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://localhost:5432/gatekeeper
    username: postgres
    password: postgres
  jpa:
    show-sql: true

security:
  jwt:
    secret-key: vLOzpBuO6M3TSDSg0XdlNj3Dg2kGM90ui+Fv66Xzc7o=
    expiration-seconds: 60000